spring:
  application:
    name: fitpower
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  output:
    ansi:
      enabled: always # permite ver el log como colores
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true