version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gestion_fitpower
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
    driver: local

